version: "3.7"
services:
    mealie-frontend:
        container_name: mealie-frontend
        image: hkotel/mealie:frontend-v1.0.0beta-4
        restart: unless-stopped
        depends_on:
            - mealie-api
        volumes:
          - ./data/:/app/data/:Z
        networks:
            - psql_backend
            - mealie_frontend
        environment:
            API_URL: http://mealie-api:9000
        expose:
            - 3000
        labels:
            traefik.enable: true
            traefik.http.routers.mealie.rule: Host(`mealie.maxbachmann.de`)
            traefik.http.routers.mealie.entrypoints: websecure
            traefik.http.routers.mealie.tls.certresolver: netcup
            traefik.http.services.mealie.loadbalancer.server.port: 3000
            traefik.docker.network: mealie_frontend

    mealie-api:
        container_name: mealie-api
        image: hkotel/mealie:api-v1.0.0beta-4
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 1000M
        # depends_on:
            # - "psql"
        volumes:
          - ./data/:/app/data/:Z
        networks:
            - psql_backend
            - mealie_frontend
        environment:
            ALLOW_SIGNUP: 'true'
            PUID: 1000
            PGID: 1000
            TZ: Europe/Berlin
            MAX_WORKERS: 1
            WEB_CONCURRENCY: 1
            BASE_URL: https://mealie.maxbachmann.de

            # Database Settings
            DB_ENGINE: postgres
            POSTGRES_USER: mealie
            POSTGRES_PASSWORD: <password>
            POSTGRES_SERVER: psql
            POSTGRES_PORT: 5432
            POSTGRES_DB: mealie

networks:
    psql_backend:
        external: true
    mealie_frontend:
        name: mealie_frontend
