version: '3.1'

services:
    psql:
        container_name: psql
        hostname: psql
        image: postgres:14
        restart: always
        volumes:
            - ./conf:/etc/postgresql
            - ./data:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/psql-password
            PGDATA: /var/lib/postgresql/data/pgdata
        networks:
            - backend
        secrets:
            - psql-password
#        healthcheck:
#            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
#            interval: 10s
#            timeout: 5s
#            retries: 5

networks:
    backend:
        name: psql_backend

secrets:
    psql-password:
        file: ../.secrets/psql/password
        name: psql-password